import React from 'react'
import useScroll from '../../hooks/useScroll'

const Blog = () => {
  useScroll();
  return (
    <div className='container mx-auto'>
        <div className='mb-4'>
            <h2 className='mb-3'>Blog</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias quasi nihil a optio voluptatum suscipit hic. Possimus ducimus, ratione repellendus optio sunt quas? Reprehenderit natus nostrum expedita ratione eos corrupti, consequatur doloremque eveniet corporis quaerat sint necessitatibus, beatae rem quae blanditiis? Quasi sunt atque ea beatae earum doloremque laborum voluptatum molestiae, ipsam iste natus tempore temporibus et nostrum cupiditate maxime animi! Voluptas similique cupiditate quaerat tempora maxime neque aliquam, quos iure nesciunt incidunt veritatis amet soluta, fugit at quasi pariatur. Nisi esse quisquam labore accusantium corporis eaque, recusandae minima molestiae doloremque magnam dolorum ex delectus sapiente suscipit iste. Laudantium voluptatem eum expedita non labore fugiat quaerat, consectetur ullam vitae explicabo officia animi aliquid incidunt, earum dolores similique beatae blanditiis pariatur rerum necessitatibus excepturi facere nesciunt. Animi ipsa officia quam aliquid quidem atque quia in porro consequuntur beatae aut nisi, impedit blanditiis corrupti. Quia assumenda, in ullam labore tempore excepturi laboriosam delectus consectetur unde, eaque enim quo molestias numquam quam sapiente repudiandae dolore id. Ipsam ullam similique illum quisquam consequatur molestias neque accusantium, ad sunt odio corrupti. Consequatur aut maiores, minus natus repellendus, culpa dignissimos non quod adipisci, hic praesentium rem iure aperiam perferendis doloremque. Maxime quidem labore incidunt quos eaque?</p>
        </div>
        <div className='mb-4'>
            <h2 className='mb-3'>Blog</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias quasi nihil a optio voluptatum suscipit hic. Possimus ducimus, ratione repellendus optio sunt quas? Reprehenderit natus nostrum expedita ratione eos corrupti, consequatur doloremque eveniet corporis quaerat sint necessitatibus, beatae rem quae blanditiis? Quasi sunt atque ea beatae earum doloremque laborum voluptatum molestiae, ipsam iste natus tempore temporibus et nostrum cupiditate maxime animi! Voluptas similique cupiditate quaerat tempora maxime neque aliquam, quos iure nesciunt incidunt veritatis amet soluta, fugit at quasi pariatur. Nisi esse quisquam labore accusantium corporis eaque, recusandae minima molestiae doloremque magnam dolorum ex delectus sapiente suscipit iste. Laudantium voluptatem eum expedita non labore fugiat quaerat, consectetur ullam vitae explicabo officia animi aliquid incidunt, earum dolores similique beatae blanditiis pariatur rerum necessitatibus excepturi facere nesciunt. Animi ipsa officia quam aliquid quidem atque quia in porro consequuntur beatae aut nisi, impedit blanditiis corrupti. Quia assumenda, in ullam labore tempore excepturi laboriosam delectus consectetur unde, eaque enim quo molestias numquam quam sapiente repudiandae dolore id. Ipsam ullam similique illum quisquam consequatur molestias neque accusantium, ad sunt odio corrupti. Consequatur aut maiores, minus natus repellendus, culpa dignissimos non quod adipisci, hic praesentium rem iure aperiam perferendis doloremque. Maxime quidem labore incidunt quos eaque?</p>
        </div>
        <div className='mb-4'>
            <h2 className='mb-3'>Blog</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias quasi nihil a optio voluptatum suscipit hic. Possimus ducimus, ratione repellendus optio sunt quas? Reprehenderit natus nostrum expedita ratione eos corrupti, consequatur doloremque eveniet corporis quaerat sint necessitatibus, beatae rem quae blanditiis? Quasi sunt atque ea beatae earum doloremque laborum voluptatum molestiae, ipsam iste natus tempore temporibus et nostrum cupiditate maxime animi! Voluptas similique cupiditate quaerat tempora maxime neque aliquam, quos iure nesciunt incidunt veritatis amet soluta, fugit at quasi pariatur. Nisi esse quisquam labore accusantium corporis eaque, recusandae minima molestiae doloremque magnam dolorum ex delectus sapiente suscipit iste. Laudantium voluptatem eum expedita non labore fugiat quaerat, consectetur ullam vitae explicabo officia animi aliquid incidunt, earum dolores similique beatae blanditiis pariatur rerum necessitatibus excepturi facere nesciunt. Animi ipsa officia quam aliquid quidem atque quia in porro consequuntur beatae aut nisi, impedit blanditiis corrupti. Quia assumenda, in ullam labore tempore excepturi laboriosam delectus consectetur unde, eaque enim quo molestias numquam quam sapiente repudiandae dolore id. Ipsam ullam similique illum quisquam consequatur molestias neque accusantium, ad sunt odio corrupti. Consequatur aut maiores, minus natus repellendus, culpa dignissimos non quod adipisci, hic praesentium rem iure aperiam perferendis doloremque. Maxime quidem labore incidunt quos eaque?</p>
        </div>
    </div>
  )
}

export default Blog